name: chat_server
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.4.0 <3.4.2'

dependencies:
  args: ^2.4.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  dotenv: ^4.2.0
  postgres: ^3.2.1
  get_it: ^7.7.0
  drift_postgres: ^1.2.3
  drift: ^2.18.0
  uuid: ^4.4.0
  dart_jsonwebtoken: ^2.14.0

dev_dependencies:
  http: ^1.1.0
  lints: ^3.0.0
  test: ^1.24.0
  very_good_analysis: ^5.1.0
  build_runner: ^2.4.10
  drift_dev: ^2.18.0
